logging:
    level:
        org:
            springframework: info
#            hibernate:
#                type:
#                    descriptor:
#                        sql: trace

spring:
    jackson:
        time-zone: Asia/Seoul
    profiles:
        active: ${ACTIVE}
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    thymeleaf:
        prefix: classpath:/templates/
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
#        properties:
#            hibernate:
#                show_sql: true
#                use_sql_comments: true
#                highlight_sql: true
#                format_sql: true
#        show-sql: true
        generate-ddl: true
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQLDialect
    jwt:
        secret: ${JWT_SECRET}
        expired-access: ${EXPIRED_ACCESS}
        expired-refresh: ${EXPIRED_REFRESH}
    cloud:
        gcp:
            storage:
                credentials:
                    location: ${KEY_LOCATION}
                project-id: ${KEY_PROJECT_ID}
                bucket: ${BUCKET}
