spring:
  datasource:
    url: jdbc:mysql://${CONNECT_ADDRESS}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE}